# Generated by Django 6.0.5 on 2026-06-09 18:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('do_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('planned', 'Zaplanowane'), ('in_production', 'W produkcji'), ('in_delivery', 'W dostawie'), ('delivered', 'Dostarczone'), ('cancelled', 'Anulowane')], default='planned', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_orders', to='clients.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_orders', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandingOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Pn'), (1, 'Wt'), (2, ' Śr'), (3, 'Czw'), (4, 'Pt'), (5, 'Sb'), (6, 'Nd')], help_text='0 = Monday, 6 = Sunday', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('quantity', models.IntegerField()),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_orders', to='clients.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_orders', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
