# Generated by Django 6.0.5 on 2026-07-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_supplier_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='nip',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
