# Generated by Django 6.0.5 on 2026-07-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_route_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nip',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
