# Generated by Django 6.0.5 on 2026-07-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientStock',
            fields=[
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='products.ingredient')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='min_stock_level',
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('product', 'ingredient')},
        ),
    ]
